<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="xuxiaochande-MacBook-Pro.local" ignored="0" name="Default test" tests="64" failures="18" timestamp="23 七月 2019 07:54:39 GMT" time="25.352" errors="0">
  <testcase name="bankInfoCollectEndpointRequest" time="0.883" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.394" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.368" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.444" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.406" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.37" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.345" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.405" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.406" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 1 and 17 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of account_number should be between 1 and 17 when bank_country_code is 'US'"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.404" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.405" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.411" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 6 and 9 when bank_country_code is &amp;apos;AU&amp;apos;&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of account_number should be between 6 and 9 when bank_country_code is 'AU'"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.388" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.412" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.406" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 6 and 9 when bank_country_code is &amp;apos;AU&amp;apos;&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of account_number should be between 6 and 9 when bank_country_code is 'AU'"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 8 and 20 when bank_country_code is &amp;apos;CN&amp;apos;&amp;quot;}] but found [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of account_number should be between 8 and 20 when bank_country_code is 'CN'"}] but found [{"success":"Bank details saved"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.408" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 8 and 20 when bank_country_code is &amp;apos;CN&amp;apos;&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of account_number should be between 8 and 20 when bank_country_code is 'CN'"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.408" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.342" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.475" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.369" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.341" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.357" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.362" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.349" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.365" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.408" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;The swift code is not valid for the given bank country code: CN&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"The swift code is not valid for the given bank country code: CN"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;The swift code is not valid for the given bank country code: CN&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"The swift code is not valid for the given bank country code: CN"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.345" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.336" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.412" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of &amp;apos;swift_code&amp;apos; should be either 8 or 11&amp;quot;}] but found [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of 'swift_code' should be either 8 or 11"}] but found [{"success":"Bank details saved"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.34" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;Length of &amp;apos;swift_code&amp;apos; should be either 8 or 11&amp;quot;}] but found [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"Length of 'swift_code' should be either 8 or 11"}] but found [{"success":"Bank details saved"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.337" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.475" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.339" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.374" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.41" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.407" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.409" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.408" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.344" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;error&amp;quot;:&amp;quot;&amp;apos;aba&amp;apos; is required when bank country code is US&amp;quot;}] but found [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"error":"'aba' is required when bank country code is US"}] but found [{"success":"Bank details saved"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.338" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.403" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.346" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.339" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
  <testcase name="bankInfoCollectEndpointRequest" time="0.373" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.339" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.337" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.341" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.372" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest"/>
  <testcase name="bankInfoCollectEndpointRequest" time="0.338" classname="xuxiaochan.test.airwallex.BankInfoEndpointTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;success&amp;quot;:&amp;quot;Bank details saved&amp;quot;}] but found [{&amp;quot;error&amp;quot;:&amp;quot;Length of account_number should be between 7 and 11 when bank_country_code is &amp;apos;US&amp;apos;&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"success":"Bank details saved"}] but found [{"error":"Length of account_number should be between 7 and 11 when bank_country_code is 'US'"}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at xuxiaochan.test.airwallex.BankInfoEndpointTest.bankInfoCollectEndpointRequest(BankInfoEndpointTest.java:129)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- bankInfoCollectEndpointRequest -->
</testsuite> <!-- Default test -->
